#!/usr/bin/env bash

set -e

ENVIRONMENT=$1

red='\e[1;31m'
blue='\e[1;34m'
endColor='\e[0m'

if [[ -z ${ENVIRONMENT} ]]
then
    echo "usage $(basename "$0") ENVIRONMENT"
    echo ""
    echo "  deploys the repository"
    exit -1
fi

BRANCH_NAME="env_${ENVIRONMENT}"

# TODO check that environment name is standard, wait for confirmation otherwise
# TODO check that head is clean

echo -e "Deploying environment ${red}${ENVIRONMENT}${endColor} as branch ${blue}${BRANCH_NAME}${endColor} from HEAD"

echo -e "updating git ref..."
git update-ref refs/heads/${BRANCH_NAME} HEAD

echo -e "pushing to remote repository..."
git push -f origin ${BRANCH_NAME}:${BRANCH_NAME}

echo "done"