#!/bin/bash

TARGET=${1:-.payload.message}
OPTIONS=$2

if [ $OPTIONS == "tiny" ]
then
    while read -r line; do
        echo $(echo "$line" | jq -r .payload.requestMethod) $(echo "$line" | jq -r ${TARGET})
    done
else
    while read -r line; do
        echo $(echo "$line" | jq .time) $(echo "$line" | jq -r .corr) $(echo "$line" | jq -r ${TARGET})
    done
fi