#!/bin/bash

#set -e

DURATION="1week"

for repo in `find ~/repos -type d -name .git`; do
    cd $repo
    
    REPO_LOG=$(git --no-pager log --since="$DURATION" --pretty='format:%h %ci %s')
    if [[ $REPO_LOG != '' ]]
    then
        echo "==== ${repo} ===="
        git --no-pager log --since="$DURATION" --pretty='format:%h %ci %s'
        echo ""
        echo ""
    fi
done